### ISSUE TITLE
when I try to run python make_dataset.py config.yaml I get the following error.

### ISSUE THREAD

**Issue by pinskaner** [johnarevalo/cnn-bcdr#1]
![ekran alintisi](https://cloud.githubusercontent.com/assets/23073635/24924832/e03fa110-1efe-11e7-8859-00ac3a2e55f2.JPG)

**Comment by johnarevalo** [comment]
Could you remove the ```try-catch``` statement of this [line](https://github.com/johnarevalo/cnn-bcdr/blob/0a1d911ad85cf7566527db1caf0342f277aff921/utils.py#L297) and run again?. Please paste plain text the output, not an image.

**Comment by johnarevalo** [comment]
Closed due to inactivity
