### ISSUE TITLE
Undefined Metric Warning

### ISSUE THREAD

**Issue by pinarhepsag** [johnarevalo/cnn-bcdr#2]
When I run evaluate.py, I am getting an error in Anaconda2\lib\site_packages\sklearn\metrics\classification.py
**UndefinedMetricWarning: F-score is _ill-defined and being set to 0.0 due to no predicted samples**

**Comment by johnarevalo** [comment]
Can you check the ```y_pred``` value?. This is related to either always ```True``` or always ```False``` prediction.

**Comment by johnarevalo** [comment]
Closed due to inactivity
