### ISSUE TITLE
Link in readme.md is broken, data can't be downloaded

### ISSUE THREAD

**Issue by GrigoriiTarasov** [johnarevalo/cnn-bcdr#5]
http://bcdr.inegi.up.pt/

**Comment by johnarevalo** [comment]
We are moving the data to a new server. Sorry for the inconvenience.

**Comment by shawnyuen** [comment]
@johnarevalo when BCDR-F03 dataset could be downloaded?

**Comment by johnarevalo** [comment]
There is a mirror for the website: 

https://bcdr.ceta-ciemat.es/

Registration and a non-disclosure agreement document is required.

**Comment by lyzinfo** [comment]
Dataset can not be downloaded in https://bcdr.ceta-ciemat.es/, please let me know the dataset server.

**Comment by johnarevalo** [comment]
Server https://bcdr.ceta-ciemat.es/ is now back online
