### ISSUE TITLE
Not able to obtain BCDR dataset

### ISSUE THREAD

**Issue by BhavyaMaya** [johnarevalo/cnn-bcdr#7]
I have been trying to obtain the BCDR dataset. I have emailed several of the contacts listed on the website but have not received any response from them. Can you please provide an email address of someone who would be able to provide access to the dataset?

**Comment by johnarevalo** [comment]
The access to this dataset is at solely discretion of the institution. I noticed some of the researchers are not part of the group anymore. I suggest you to search for their most recent positions and reach them out.

Closing it.
